name: Mutex-Next Gen

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'URL repo kernel (kosongkan untuk pakai repo ini sendiri)'
        required: true
        default: "https://github.com/Aciss21/kernel_xiaomi_sm6150.git"
        type: string
      branch:
        description: "Branch"
        required: true
        default: "16.2"
        type: string
      ksu:
        description: "KernelSU"
        required: true
        default: "none"
        type: choice
        options:
          - none
          - KernelSU-Next

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actionhippie/swap-space@v1
        with:
          size: 15G
                  
      - name: 📦 Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev dwarves bc rsync cpio python3 python3-pip git curl wget make lz4 zip unzip ccache zstd
          sudo apt install -y fakeroot device-tree-compiler libdw-dev pkg-config lld llvm tar

      - name: 📥 Clone Kernel Source
        run: |
          rm -rf kernel
          git clone -q --depth=1 -b ${{ github.event.inputs.branch }} ${{ github.event.inputs.repo }} kernel

      - name: ✅ Verify Swap
        run: free -h

      - name: 🧩 Setup KernelSU
        if: ${{ github.event.inputs.ksu == 'KernelSU-Next' }}
        working-directory: kernel
        run: |
          curl -LSs "https://raw.githubusercontent.com/Mr-Morat/KernelSU-Next/stable/kernel/setup.sh" | bash -s syscall

      - name: 🔨 Build Kernel
        working-directory: kernel
        run: |
          bash copyright
