name: Mutex-Next Gen

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'URL repo kernel (kosongkan untuk pakai repo ini sendiri)'
        required: true
        default: "https://github.com/Aciss21/Paranoid_Courbet.git"
        type: string
      branch:
        description: "Branch"
        required: true
        default: "ksu"
        type: string
        
      ksu:
        description: "KernelSU"
        required: true
        default: "none"
        type: choice
        options:
          - none
          - KernelSU-Next

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev dwarves bc rsync cpio python3 python3-pip git curl wget make lz4 zip unzip ccache zstd
          sudo apt install -y fakeroot device-tree-compiler libdw-dev pkg-config lld llvm tar          
     steps:
      - uses: actions/checkout@v2
      - uses: actionhippie/swap-space@v1
        with:
          size: 10G
          
      - name: 📥 Clone Kernel Source
        run: |
          git clone -q --depth=1 -b ${{ github.event.inputs.branch }} ${{ github.event.inputs.repo }} kernel

      - name: 🧩 Setup KernelSU
        if: ${{ github.event.inputs.ksu == 'KernelSU-Next' }}
        working-directory: kernel
        run: |
          curl -LSs "https://raw.githubusercontent.com/orlan-kecap/KernelSU-Next/stable/kernel/setup.sh" | bash -s syscall
          
      - name: ⛓️ Setup Toolchain        
        working-directory: kernel
        run: |
         bash setup.sh
        
      - name: 🔨 Build Kernel
        working-directory: kernel              
        run: |         
          bash copyright
